export const FETCH_FILMS_START = "FETCH_FILMS_START";
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILMS_FAIL = "FETCH_FILMS_FAIL";
export const CHOOSE_FILM = "CHOOSE_FILM";
export const FETCH_TIMES_START = "FETCH_TIMES_START";
export const FETCH_TIMES_SUCCESS = "FETCH_TIMES_SUCCESS";
export const FETCH_TIMES_FAIL = "FETCH_TIMES_FAIL";
